### ISSUE TITLE
provs参数和rcl参数是什么意思？

### ISSUE THREAD

**Issue by fumengze** [datugou/spiders#2]
比如这条请求：https://aiqicha.baidu.com/s?q=%E6%96%B0%E5%8D%8E%E4%BA%BA%E5%AF%BF%E4%BF%9D%E9%99%A9%E8%82%A1%E4%BB%BD%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8&f={%22provinceCode%22:%22110000%22,%22regCapLevel%22:%22level1%22}
我不清楚{}内的数据是什么意思。

**Comment by datugou** [comment]
![screenshot_202102221730520000](https://user-images.githubusercontent.com/30107520/108689034-9051e480-7533-11eb-8d3c-36aea70eb471.PNG)
分别对应这些筛选项，目的是把搜索结果的量控制在 1000 之内

**Comment by fumengze** [comment]
这些参数地址在哪里呢？怎样获取所有的参数

**Comment by datugou** [comment]
![b43eec2f629290b30ff66513beeb88b](https://user-images.githubusercontent.com/30107520/108697557-fb081d80-753d-11eb-940b-18129d825c67.png)
浏览器打开开发者工具，每种筛选项试一下，就能看懂具体的对应参数了

**Comment by fumengze** [comment]
好的，谢谢，我正在二次开发这两个脚本。
