### ISSUE TITLE
抖音爬虫不能用了，按文档要求操作报错了，出现下面的问题，请问怎么解决，我是新手小白

### ISSUE THREAD

**Issue by CoderLJJ** [datugou/spiders#4]
user_name = js['aweme_list'][0]['author']['nickname']
IndexError: list index out of range

**Comment by datugou** [comment]
测试了一下，没有问题。根据错误提示是没有获取到用户的信息，是不是分享链接填错了，你是手填的还是粘贴的

**Comment by CoderLJJ** [comment]
我用这个链接就报错了 https://v.douyin.com/eB477pt/  ，我用别的链接就可以正常抓取

**Comment by datugou** [comment]
> 我用这个链接就报错了 https://v.douyin.com/eB477pt/ ，我用别的链接就可以正常抓取

试了一下，发现获取视频链接的时候，翻到最后一页，没内容。所以导致读取用户名的时候出错。
所以把读取用户名的操作改在第一页进行。已经修改了代码。
