### ISSUE TITLE
抖音视频的用Linux 系统文件前面对多一个反斜杠\是什么原因呢？ 

### ISSUE THREAD

**Issue by luolovehk** [datugou/spiders#5]
如题

**Comment by datugou** [comment]
不清楚啊，没用过linux。只知道 Windows 的地址写法是 "d:\Python\workplace\"，linux的写法是 "d:/Python/workplace/"，会不会和这个有关系

**Comment by luolovehk** [comment]
> 不清楚啊，没用过linux。只知道 Windows 的地址写法是 "d:\Python\workplace"，linux的写法是 "d:/Python/workplace/"，会不会和这个有关系

我找到原因了。'\\'  用了转义
